library(tidyverse)
library(rvest)
library(stringr)
library(magrittr)
myurl <- ("https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=soc_politicalscience")
myhtml<-read_html(myurl)

mynodes<-html_nodes(myhtml,"td")
tex<-as.list(html_text(mynodes))
tex<-gsub("[0-9]",NA,tex)
tex<-as.list(na.omit(tex))
